### ISSUE TITLE
[BUG] - Password too generic error shown even if the password is strong if the email is not in the form of abc@abc.com

### ISSUE THREAD

**Issue by thejaswinidm** [gcivil-nyu-org/wed-fall24-team5#331] opened 2024-11-16 00:06 UTC
**Description**
When you try to create an account if the email is given as abc@abc and then fill out other fields , give a good password it shows the below error saying the password is generic whereas the issue is with email provided.
**Steps to Reproduce**
Go to login;
1. email: abc@abc
2. fill the password as:6PkpcjNI^CP 

**Expected Behavior**
It should show that email is not in the correct format.

**Screenshots or Code Snippets (required)**
<img width="1143" alt="Screenshot 2024-11-15 at 7 06 04 PM" src="https://github.com/user-attachments/assets/b7ab7a9e-e574-4018-8d76-8feec5064595">

<img width="1060" alt="Screenshot 2024-11-15 at 7 06 21 PM" src="https://github.com/user-attachments/assets/3258318f-fbf1-4a91-9c9f-9f04044feac7">

**Comment by arsalananwar11** [comment] 2024-11-16 02:17
Hey @thejaswinidm, thanks for testing our application pointing this out. This is a known issue which has been flagged by our classmate earlier. We have also fixed it and it should be integrated with production once we test everything on development.

https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/313

Hence, closing this because its a duplicate of Issue 313

**Closed by arsalananwar11** 2024-11-16 02:17 UTC
Labels: bug
